# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/alessio/shellescape
%global goipath         github.com/alessio/shellescape
Version:                1.4.1

%gometa

%global common_description %{expand:
Escape arbitrary strings for use as command line arguments.}

%global golicenses      LICENSE
%global godocs          AUTHORS CODE_OF_CONDUCT.md README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Escape arbitrary strings for use as command line arguments

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc AUTHORS CODE_OF_CONDUCT.md README.md
%{_bindir}/*

%gopkgfiles

%changelog
* Mon Jan 18 18:41:41 EST 2021 anthr76 <hello@anthonyrabbito.com> - 1.4.1-1
- Initial package

